### ISSUE TITLE
See if we can point to a `*.rmi.org` domain

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/rmi-pacta.github.io#4]
Currently, the site will build at `rmi-pacta.github.io`

IF we decide that having a technical blog is useful, it likely makes more sense to have it live somewhere around:
https://pacta.rmi.org/

Note: Consider looking into how `tidyverse` does it, since they build a site in a similar way, and use the domain https://www.tidyverse.org/

**Comment by AlexAxthelm** [comment]
cc @hodie Any thoughts on where a dev blog could live?

**Comment by hodie** [comment]
I think it's fine to have the blog outside of rmi.org to stress the open-source nature of PACTA. To me RMI.org is about services, professional engagement etc. COP and P4I fall neatly into this as well. But anything related how to develop or use PACTA code lives more naturally within Github.

**Comment by jdhoffa** [comment]
In that case, I will close this issue!
